version: '3.8'
services:
  app:
    container_name: movie-db
    build: .
    command: python /code/app.py
    volumes:
      - .:/code
    ports:
        - 8000:8000
  db:
    container_name: pg_container_test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_test
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"