version: '3.8'
services:  
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - "./database_scripts/2-movies.sql:/docker-entrypoint-initdb.d/2-movies.sql"
      - "./database_scripts/3-actors.sql:/docker-entrypoint-initdb.d/3-actors.sql"
      - "./database_scripts/4-genres.sql:/docker-entrypoint-initdb.d/4-genres.sql"
      - "./database_scripts/5-reviews.sql:/docker-entrypoint-initdb.d/5-reviews.sql"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  app:
    container_name: movie-db
    build: .
    command: python /code/app.py
    volumes:
      - .:/code
    ports:
        - 8000:8000